services:
  backend:
    build:
      context: ./backend
    container_name: payments_backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:5432/${DATABASE_NAME}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    expose:
      - 8000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    container_name: payments_db
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgdata:
