from environs import Env


env = Env()
env.read_env()

DB_URL = env("DATABASE_URL")
DATABASE_HOST = env("DATABASE_HOST")
DATABASE_PORT = env("DATABASE_PORT")
DATABASE_NAME = env("DATABASE_NAME")
DATABASE_USER = env("DATABASE_USER")
DATABASE_PASSWORD = env("DATABASE_PASSWORD")
FRONTEND_URL = env("FRONTEND_URL")
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK = env("STRIPE_WEBHOOK")
